name: image
channels:
  - conda-forge
dependencies:
  - lue
  - netcdf4
  - psutil
  - tqdm
  - rasterio
  - openpyxl
  - sphinx
  - sphinx_rtd_theme
  - linkify-it-py
  - recommonmark
  - myst-parser=0.19.1
